CommandBot -> Commando
paiza-learning/warriorsbot pull request #27
Opened 2021-02-12 15:47 UTC by cwd-k2

CommandBot から Commando へ移行

2021-02-12 15:56 UTC, cwd-k2 commented
`paizaIO` コマンドが `paizaio` コマンドに変更されています (Commando の制約)

2021-02-15 15:20 UTC, s10akir requested changes
![](https://user-images.githubusercontent.com/34061817/107964549-c13e9080-6fec-11eb-8446-eae59beeb394.png)

2021-02-15 15:20 UTC, s10akir commented on src/commands/paiza/moja.ts
> +const mojamojaURL = 'https://www.mojamoja.cloud/api/v1/environment/latest';
:100:

2021-02-15 15:20 UTC, s10akir commented on src/commands/paiza/moja.ts
> +export default class HelloCommand extends Command {
HelloCommandではないっすね

2021-02-15 15:20 UTC, s10akir commented on src/commands/paiza/paizaIO.ts
> +export default class HelloCommand extends Command {
ここもHelloCommandではないっすね

2021-02-15 15:20 UTC, s10akir commented on src/commands/paiza/paizaIO.ts
> +async function paizaIO(args: string[], contentBody: string): Promise<string> {
paizaIOは主語であって振る舞いではないので命名的にpaizaIOはなんか違和感あります
（ここで対応しなくてもよし）

2021-02-15 15:20 UTC, s10akir commented on src/commands/paiza/reactme.ts
> +export default class HelloCommand extends Command {
HelloCommandではないっすね

2021-02-15 15:20 UTC, s10akir commented on src/index.ts
> +});
CommandoのclientがDiscord.jsのclientのラッパーなのでDiscord.client自体が必要ないと思ってるんですがちがいます？

2021-02-15 18:56 UTC, cwd-k2 commented on src/index.ts
> +});
https://github.com/discordjs/Commando/blob/f1ff9f5c937efd1b2ee0ef25c7b11f60d62a1e19/src/client.js#L10
本当だ...
直しておきます

2021-02-16 12:56 UTC, s10akir approved these changes
![](https://user-images.githubusercontent.com/34061817/108065642-aaa64100-70a1-11eb-9655-9c034b262c00.png)

2021-02-16 12:56 UTC, merged